/** Injection tokens para la inyección de dependencias en NestJS */
export const TOKENS = {
    // Repositorios
    COMPANY_REPOSITORY: 'COMPANY_REPOSITORY',
    USER_REPOSITORY: 'USER_REPOSITORY',
    INVOICE_REPOSITORY: 'INVOICE_REPOSITORY',
    CUSTOMER_REPOSITORY: 'CUSTOMER_REPOSITORY',
    CERTIFICATE_REPOSITORY: 'CERTIFICATE_REPOSITORY',
    PERSON_REPOSITORY: 'PERSON_REPOSITORY',
    ROLE_REPOSITORY: 'ROLE_REPOSITORY',
    API_KEY_REPOSITORY: 'API_KEY_REPOSITORY',
    WEBHOOK_REPOSITORY: 'WEBHOOK_REPOSITORY',
    // Servicios de infraestructura (puertos)
    XML_GENERATOR: 'XML_GENERATOR',
    SIGNER_SERVICE: 'SIGNER_SERVICE',
    DIAN_CLIENT: 'DIAN_CLIENT',
    CERTIFICATE_ENCRYPTOR: 'CERTIFICATE_ENCRYPTOR',
    TOKEN_MANAGER: 'TOKEN_MANAGER',
    EMAIL_SENDER: 'EMAIL_SENDER',
} as const;
